"C#":
 - ./**/*.cs
 - ./**/*.csproj

"Powershell":
 - ./**/*.ps1
 - ./**/*.psm1

"SQL":
 - db/**/*
 - ./**/*.sql

"Solidity":
 - ./**/*.sol

"unit-tests":
 - src/*.Tests.*/**/*
 - src/*.Tests/**/*
 - src/*.Tests.Integration.*/**/*
 - src/*.Tests.Integration/**/*

".NET update":
 - src/global.json

"Config Change":
 - src/**/*.json

"Static Code Analysis Rules":
 - src/CodeAnalysis.ruleset

"Migration Script":
 - tools/MigrationScripts/**/*

"Legal Text":
 - tools/LegalText/**/*

"Change Log":
 - CHANGELOG.md

"Read Me":
 - README.md

"Setup":
 - SETUP.md

"github-actions":
 - .github/workflows/*.yml

"Credfeto.ChangeLog":
 - src/Credfeto.ChangeLog/**/*

"Credfeto.ChangeLog.Cmd":
 - src/Credfeto.ChangeLog.Cmd/**/*

"Credfeto.ChangeLog.Tests":
 - src/Credfeto.ChangeLog.Tests/**/*

