name: .NET Core [Release]

on:
  push:
     branches:
       - 'release/*'
       - 'hotfix/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 0
    - name: Fetch tags and master
      run: |
        git fetch --tags
        echo REF: $GITHUB_REF
        echo SHA: $GITHUB_SHA
        echo GIT_BRANCH=$GITHUB_REF >> $GITHUB_ENV
        git branch --remote
    - name: Determine .net core version
      uses: credfeto/action-dotnet-version-detect@v1.2.0
    - name: Setup .NET Core (Old)
      uses: actions/setup-dotnet@v1.9.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        dotnet-version: 5.0.403
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.9.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Enable dotnet tools
      run: dotnet new tool-manifest
    - name: Install Build Version Tool
      run: dotnet tool install --local FunFair.BuildVersion
    - name: Install Multi-Push Tool
      run: dotnet tool install --local Credfeto.Package.Push
    - name: Install Changelog Tool
      run: dotnet tool install --local Credfeto.Changelog.Cmd
    - name: Set Define Build Version
      run: dotnet buildversion --BuildNumber $GITHUB_RUN_NUMBER
    - name: Create Release Notes
      run: dotnet changelog --changelog CHANGELOG.md --extract RELEASE_NOTES.md --version ${{ env.BUILD_VERSION }}
    - id: release-notes
      uses: juliangruber/read-file-action@v1
      with:
        path: RELEASE_NOTES.md
    - name: Build with dotnet
      working-directory: ./src
      run: dotnet build --configuration Release /p:Version=${{ env.BUILD_VERSION }}
    - if: ${{ && secrets.NUGET_API_KEY != '' }}
      name: Pack tool
      working-directory: ./src
      run: dotnet pack --configuration Release /p:Version=${{ env.BUILD_VERSION }} --no-restore --output ../dist
      env:
        ReleaseNotes: ${{ steps.release-notes.outputs.content }}
    - if: ${{ && secrets.NUGET_API_KEY != '' }}
      name: Publish
      run: dotnet pushpackages -folder dist --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_FEED }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.BUILD_VERSION }}
        release_name: Release ${{ env.BUILD_VERSION }}
        body_path: RELEASE_NOTES.md
        draft: false
        prerelease: false
