name: Find branches without PR's

on:
  push:
    branches:
      - "main"
  schedule:
  - cron: "0 0 * * *"

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.SOURCE_PUSH_TOKEN }}

      - id: set-matrix
        run: echo "::set-output name=branches::$(git branch --remote --format='%(refname:short)' | grep -Po 'origin/\K[^.*]*' | grep -vE 'HEAD|release/|hotfix/' | jq -R -s -c 'split("\n")[:-1]')"
    outputs:
      branches: ${{ steps.set-matrix.outputs.branches }}

  check-branch:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ${{ fromJson(needs.build-matrix.outputs.branches) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.SOURCE_PUSH_TOKEN }}

      - id: detection
        run: |
          echo "::set-output name=defaultbranch::$(git remote show origin | grep -Po 'HEAD\sbranch:\s+\K[^.*]*')"
      - run: |
          echo 'Found: ${{ matrix.branch }}'

      # On Default branch
      - if: ${{ steps.detection.outputs.defaultbranch == matrix.branch }}
        run: echo "On Default branch - don't do anything"


      # On Non-Default branch
      - if: ${{ steps.detection.outputs.defaultbranch != matrix.branch }}
        run: echo "On non-default branch"

      - if: ${{ steps.detection.outputs.defaultbranch != matrix.branch }}
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          branch: ${{ matrix.branch }}
      - if: ${{ steps.detection.outputs.defaultbranch != matrix.branch }}
        run: echo "Pull Request ${number} (${sha})"
        env:
          number: ${{ steps.find-pull-request.outputs.number }}
          sha: ${{ steps.find-pull-request.outputs.head-sha }}