name: Find branches without PR's

on:
  push:
    branches:
      - "main"
  schedule:
  - cron: "0 0 * * *"

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - id: set-matrix
        run: echo "::set-output name=branches::$(curl https://endoflife.date/api/nodejs.json | jq -c '[.[] | select(.eol > (now | strftime("%Y-%m-%d"))) | .cycle]')"
    outputs:
      branches: ${{ steps.set-matrix.outputs.branches }}

  check-branch:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ${{ fromJson(needs.build-matrix.outputs.branches) }}
    steps:
      # - uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 0
      #     token: ${{ secrets.SOURCE_PUSH_TOKEN }}

      - run: |
          echo 'Found: ${{ matrix.branch }}'
